<?php

return [
    'MEDAL_PROFILE_STATUS_PENDING_VALUE' => 0,
    'MEDAL_PROFILE_STATUS_PENDING_NAME' => "Pending",
    'MEDAL_PROFILE_STATUS_ACTIVE_VALUE' => 1,
    'MEDAL_PROFILE_STATUS_ACTIVE_NAME' => "Active",
    'MEDAL_PROFILE_STATUS_CLOSE_VALUE' => 2,
    'MEDAL_PROFILE_STATUS_CLOSE_NAME' => "Close",
];
